// marketplaceData.ts
import { MarketplaceItem } from './MarketPlaceCard';

export const MarketPlaceData: MarketplaceItem[] = [
    {
        id: 1,
        category: 'Phone',
        price: 'Rs. 35,000',
        title: 'Oppo Reno Z 8 256',
        location: 'Manawan, Lahore',
        updatedAt: 'Updated 1 year ago',
        verified: true,
        imageUrl: require('@/assets/images/others/marketplace/oppo-reno.jpeg'),
    },
    {
        id: 2,
        category: 'Laptop',
        price: 'Rs. 53,000',
        title: 'Lenovo ThinkPad | Core i5',
        location: 'LMQ Road, Multan',
        updatedAt: 'Updated 1 year ago',
        verified: true,
        imageUrl: require('@/assets/images/others/marketplace/lenovo-thinkpad.jpeg'),
    },
    {
        id: 3,
        category: 'Phone',
        price: 'Rs. 34,500',
        title: 'Redmi Note 11 10/9.5',
        location: 'GT Road, Taxila',
        updatedAt: 'Updated 1 year ago',
        verified: true,
        imageUrl: require('@/assets/images/others/marketplace/redmi-phone.jpeg'),
    },
    {
        id: 4,
        category: 'Property',
        price: 'Rs. 34,000,000',
        title: '8 Marla Brand New Dream House',
        location: 'Bahria Town Phase 8, Lahore',
        updatedAt: 'Updated 1 year ago',
        verified: true,
        imageUrl: require('@/assets/images/others/marketplace/8mirla-plat.jpeg'),
    },
    {
        id: 5,
        category: 'Car',
        price: 'Rs. 1,250,000',
        title: 'Honda Civic 2018 Model',
        location: 'Model Town, Karachi',
        updatedAt: 'Updated 2 days ago',
        verified: true,
        imageUrl: require('@/assets/images/others/marketplace/8mirla-plat.jpeg'),
    },
    {
        id: 6,
        category: 'Furniture',
        price: 'Rs. 25,000',
        title: 'Wooden Dining Table Set',
        location: 'Gulberg, Islamabad',
        updatedAt: 'Updated 5 days ago',
        verified: true,
        imageUrl: require('@/assets/images/others/marketplace/8mirla-plat.jpeg'),
    },
];
